# This example file from a previous lecture where we ran drupal in docker compose
# in this Assignment, change it to work with the default drupal image, and change
# postgres to use a Swarm secret. More info in the README.md file.
# cmd: docker stack dploy -c {file_name} {stack_name}
version: '3.9'
services:

  drupal:
    image: drupal:9.3.13
    ports:
      - "8081:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
 
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql_password

secrets:
  psql_password:
    file: ./psql_pass.txt
    # external: true # create secret from command line , not stack responsibility to create it. (Secret exists)


volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
